const statesByZone = {
    urban: [
      "Delhi",
      "Mumbai",
      "Kolkata",
      "Chennai",
      "Bengaluru",
      "Hyderabad",
      "Ahmedabad",
      "Pune",
      "Surat",
      "Jaipur",
      "Lucknow",
      "Kanpur",
      "Nagpur",
      "Visakhapatnam",
      "Vadodara",
      "Indore",
      "Coimbatore",
      "Patna",
      "Kochi",
      "Bhopal",
      "Thane",
      "Nashik",
      "Chandigarh",
      "Gurugram"
    ],
    suburban: [
      "Goa",
      "Haryana",
      "Punjab",
      "Telangana",
      "Rajasthan",
      "Uttar Pradesh",
      "Gujarat",
      "Madhya Pradesh",
      "Tamil Nadu",
      "West Bengal"
    ],
    rural: [
      "Bihar",
      "Odisha",
      "Jharkhand",
      "Uttarakhand",
      "Himachal Pradesh",
      "Jammu and Kashmir",
      "Chhattisgarh",
      "Mizoram",
      "Arunachal Pradesh",
      "Nagaland",
      "Sikkim",
      "Tripura",
      "Assam",
      "Manipur",
      "Meghalaya",
      "Andaman and Nicobar Islands",
      "Lakshadweep",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Telangana" // Note: Some areas might be classified differently
    ]
  };
 export default statesByZone 